server:
  port: 8080
spring:
  application:
    name: JWTAPI
  datasource:
    url: jdbc:h2:mem:users_db
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
#  security:
#    user:
#      name: user
#      password: "{noop}user"
logging:
  level:
    org.springframework.security: TRACE