server:
  port: 8080
spring:
  application:
    name: backend-api
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/users_db}
    username: ${DATABASE_USERNAME:admin}
    password: ${DATABASE_PASSWORD:admin}
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY:000000000000}
        secret-key: ${AWS_SECRET_KEY:000000000000}
      s3:
        region: ${AWS_REGION:us-east-1}
        endpoint: ${AWS_ENDPOINT:http://s3.localhost.localstack.cloud:4566}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:1025}
    username: ${MAIL_USERNAME:test}
    password: ${MAIL_PASSWORD:test}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
app:
  jwt:
    secret: ${JWT_SECRET:cb10cf780d219b7cdc2ea6467953f195}
    expiration:
      minutes: ${JWT_EXPIRATION_MINUTES:60}
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173}
#logging:
#  level:
#    org.springframework.security: TRACE
# http://my-bucket.s3.localhost.localstack.cloud:4566/ffac61be-8bd9-47db-96bd-62be18423708.png